---
title: "P8105 HW5 jl6046"
author: "Brian Jo Hsuan Lee"
date: 2021-11-15
output: github_document
---

Load packages
```{r, message=FALSE}
library(tidyverse)
setwd("~/Desktop/Columbia/Fall_2021/P8105-Data_Science/HW/p8105_hw5_jl6046/")
```

Import and tidy dataset
```{r}
hom_df = 
  read_csv("./data_files/homicide-data.csv", col_types = "cdccfdfffddf") %>% 
  unite(city_state, city, state, sep = ", ") %>% 
  mutate(
    city_state = factor(city_state),
    year = str_extract(reported_date, "^\\d{4}"),
    year = as.factor(year),
    month = str_extract(reported_date, "(?<=^....)\\d{2}"),
    month = month.name[as.numeric(month)],
    month = factor(month, levels = month.name[]),
    day = str_extract(reported_date, "\\d{2}$"),
    day = as.numeric(day)
  ) %>% 
  select(
    uid, year, month, day, everything(), -reported_date
  )
```

Create a homicide table
```{r}
hom_sum_df = 
  hom_df %>% 
  group_by(city_state) %>% 
  summarize(tot_hom = n(),
            unsol_hom = sum(disposition != "Closed by arrest")) %>% 
  arrange(desc(tot_hom), desc(unsol_hom))

knitr::kable(
  hom_sum_df,
  format = "simple"
)
```

Proportion of homicides in Baltimore
```{r}
balt_hom_sum_df =
  hom_sum_df %>% 
  filter(city_state == "Baltimore, MD")

prop.test(pull(balt_hom_sum_df, unsol_hom), pull(balt_hom_sum_df, tot_hom))
```

